### PR TITLE
Check if Skript is looking for syntax.

### PR DESCRIPTION
**Pull request by WheezyGold7931**

### CODE REVIEW

**Comment by Nicofisi** [comment]
This will throw a NPE if there is no Skript..

**Comment by TonyMaster21** [comment]
No it won't because it is checking for Skript before this. If Skript isnt there the addon is disabled.

**Comment by Nicofisi** [comment]
You don't return anywhere in onEnable so it keeps loading lol

**Comment by WheezyGold7931** [comment]
@Nicofisi the plugin will disable if skript is not der

**Comment by TonyMaster21** [comment]
image

**Comment by Nicofisi** [comment]
@TonyMaster21 and in which line you stop executing the rest of the code?

**Comment by WheezyGold7931** [comment]
@Nicofisi the disable bungee master method disables the plugin

**Comment by TonyMaster21** [comment]
image

**Comment by Nicofisi** [comment]
But it doesn't stop executing the onEnable method does it..

**Pull request merged**
